server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://42.192.60.154:3306/db_spider?serverTimezone=GMT%2B8
    username: root
    password: Li_Chuang&123456$
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
